APPLICATION_NAME: metadata

# switch off ECS json logging in favor of readable localhost logs
LOGSTYLE: plain

#BASIC_AUTH_USERNAME: <YOU MUST ADD ANY USERNAME HERE IF VAULT IS DISABLED - SEE README>
#BASIC_AUTH_PASSWORD: <YOU MUST ADD ANY PASSWORD HERE IF VAULT IS DISABLED - SEE README>

# Url to this service, used as link in Pull Request validation builds
PULL_REQUEST_BUILD_URL: https://metadata-service.example.com

GIT_COMMITTER_NAME: <YOU MUST ADD SOME COMMITTER NAME HERE - SEE README>
GIT_COMMITTER_EMAIL: <YOU MUST ADD SOME COMMITTER EMAIL HERE - SEE README>

#VAULT_ENABLED: false
VAULT_SERVER: some-vault.de
VAULT_AUTH_TOKEN: <YOU MUST ADD YOUR TOKEN HERE - SEE README>
VAULT_SECRETS_CONFIG: >-
  {
    "some/path/to/secrets": [
      {"vaultKey": "BASIC_AUTH_USERNAME"},
      {"vaultKey": "BASIC_AUTH_PASSWORD"},
      {"vaultKey": "KAFKA_PASSWORD"},
      {"vaultKey": "METADATA_CHANGE_EVENTS_CONNECTION_STRING"},
      {"vaultKey": "SSH_PRIVATE_KEY"},
      {"vaultKey": "SSH_PRIVATE_KEY_PASSWORD"},
      {"vaultKey": "GITHUB_APP_JWT_SIGNING_KEY_PEM"}
    ]
  }

GITHUB_APP_ID: <YOU MUST ADD YOUR GITHUB APP ID HERE>
GITHUB_APP_INSTALLATION_ID: <YOU MUST ADD YOUR GITHUB APP INSTALLATION ID HERE>

WEBHOOKS_PROCESS_ASYNC: false

AUTH_OIDC_KEY_SET_URL: https://login.microsoftonline.com/<YOU MUST ADD CLIENT ID HERE>/discovery/v2.0/keys
AUTH_OIDC_TOKEN_AUDIENCE: <YOU MUST ADD TOKEN AUDIENCE HERE>

METADATA_REPO_URL: https://github.com/Interhyp/service-metadata-example
SSH_METADATA_REPO_URL: ssh://git@github.com/Interhyp/service-metadata-example.git

UPDATE_JOB_INTERVAL_MINUTES: 15
UPDATE_JOB_TIMEOUT_SECONDS: 30

ALERT_TARGET_REGEX: '(^https://domain[.]com/)|(@domain[.]com$)'

OWNER_ALIAS_FILTER_REGEX: '.*'

# The NOTIFICATION_CONSUMER_CONFIGS env below is an example:

#NOTIFICATION_CONSUMER_CONFIGS: >-
#  {
#    "consumerName": {
#      "types": {
#        "Owner": ["CREATED", "MODIFIED", "DELETED"],
#        "Service": ["CREATED", "MODIFIED", "DELETED"],
#        "Repository": ["DELETED"]
#      },
#      "url": "https://some.url.com/for/the/webhook"
#    },
#    "anotherConsumer": {
#      "types": {
#        "Owner": ["MODIFIED"],
#      },
#      "url": "https://another.url.com/for/another/webhook"
#    }
#  }

# Enable KAFKA communication (Azure event hub example)

#KAFKA_TOPICS_CONFIG: >-
#  {
#    "metadata-change-events": {
#      "topic": "metadata-change-events",
#      "brokers": [
#        "example.com:9093"
#      ],
#      "username": "$ConnectionString",
#      "passwordEnvVar": "METADATA_CHANGE_EVENTS_CONNECTION_STRING",
#      "authType": "PLAIN"
#    }
#  }

