POST http://localhost:8080/webhooks/vcs/github
Content-Type: application/json
User-Agent: GitHub-Hookshot/21a6bf0
X-GitHub-Delivery: eec244d0-1145-11f0-86c9-92581a6c49c8
X-GitHub-Event: check_run
X-GitHub-Hook-ID: 534612443
X-GitHub-Hook-Installation-Target-ID: 1173582
X-GitHub-Hook-Installation-Target-Type: integration

{
  "action": "requested_action",
  "check_run": {
    "id": 39981943119,
    "name": "only-valid-metadata-changes",
    "node_id": "CR_kwDONFp2Fc8AAAAJTxwJTw",
    "head_sha": "f68dc7b26d61dd672dd4d7a1531bfaaa4036c8f6",
    "external_id": "",
    "url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/check-runs/39981943119",
    "html_url": "https://github.com/interhyp-intern-test/service-metadata/runs/39981943119",
    "details_url": "https://metadata.core.dev.interhyp-azure.de/swagger-ui",
    "status": "completed",
    "conclusion": "failure",
    "started_at": "2025-04-04T11:13:16Z",
    "completed_at": "2025-04-04T11:13:18Z",
    "output": {
      "title": "Failed YAML validation",
      "summary": "There were files failing the validation. See Annotations.",
      "text": null,
      "annotations_count": 1,
      "annotations_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/check-runs/39981943119/annotations"
    },
    "check_suite": {
      "id": 36695856017,
      "node_id": "CS_kwDONFp2Fc8AAAAIiz5TkQ",
      "head_branch": "test-linting",
      "head_sha": "f68dc7b26d61dd672dd4d7a1531bfaaa4036c8f6",
      "status": "completed",
      "conclusion": "failure",
      "url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/check-suites/36695856017",
      "before": "fb246ffd0d6564814b499606bbf21f44987189b9",
      "after": "f68dc7b26d61dd672dd4d7a1531bfaaa4036c8f6",
      "pull_requests": [

      ],
      "app": {
        "id": 1173582,
        "client_id": "Iv23li0X1RdGuCmd16UZ",
        "slug": "metadata-ihyptst",
        "node_id": "A_kwPOAAJcp84AEehO",
        "owner": {
          "login": "interhyp",
          "id": 154791,
          "node_id": "E_kgDOAAJcpw",
          "avatar_url": "https://avatars.githubusercontent.com/b/154791?v=4",
          "gravatar_id": "",
          "url": "",
          "html_url": "",
          "followers_url": "",
          "following_url": "",
          "gists_url": "",
          "starred_url": "",
          "subscriptions_url": "",
          "organizations_url": "",
          "repos_url": "",
          "events_url": "",
          "received_events_url": "",
          "type": "enterprise",
          "site_admin": false
        },
        "name": "Metadata [IHYPTST]",
        "description": "",
        "external_url": "https://metadata.core.dev.interhyp-azure.de/swagger-ui",
        "html_url": "https://github.com/apps/metadata-ihyptst",
        "created_at": "2025-03-11T08:05:22Z",
        "updated_at": "2025-04-02T10:37:54Z",
        "permissions": {
          "checks": "write",
          "contents": "write",
          "metadata": "read"
        },
        "events": [
          "check_run",
          "check_suite"
        ]
      },
      "created_at": "2025-04-04T11:10:53Z",
      "updated_at": "2025-04-04T11:13:19Z"
    },
    "app": {
      "id": 1173582,
      "client_id": "Iv23li0X1RdGuCmd16UZ",
      "slug": "metadata-ihyptst",
      "node_id": "A_kwPOAAJcp84AEehO",
      "owner": {
        "login": "interhyp",
        "id": 154791,
        "node_id": "E_kgDOAAJcpw",
        "avatar_url": "https://avatars.githubusercontent.com/b/154791?v=4",
        "gravatar_id": "",
        "url": "",
        "html_url": "",
        "followers_url": "",
        "following_url": "",
        "gists_url": "",
        "starred_url": "",
        "subscriptions_url": "",
        "organizations_url": "",
        "repos_url": "",
        "events_url": "",
        "received_events_url": "",
        "type": "enterprise",
        "site_admin": false
      },
      "name": "Metadata [IHYPTST]",
      "description": "",
      "external_url": "https://metadata.core.dev.interhyp-azure.de/swagger-ui",
      "html_url": "https://github.com/apps/metadata-ihyptst",
      "created_at": "2025-03-11T08:05:22Z",
      "updated_at": "2025-04-02T10:37:54Z",
      "permissions": {
        "checks": "write",
        "contents": "write",
        "metadata": "read"
      },
      "events": [
        "check_run",
        "check_suite"
      ]
    },
    "pull_requests": [

    ]
  },
  "requested_action": {
    "identifier": "fix-formatting"
  },
  "repository": {
    "id": 878343701,
    "node_id": "R_kgDONFp2FQ",
    "name": "service-metadata",
    "full_name": "interhyp-intern-test/service-metadata",
    "private": true,
    "owner": {
      "login": "interhyp-intern-test",
      "id": 169439834,
      "node_id": "O_kgDOChlyWg",
      "avatar_url": "https://avatars.githubusercontent.com/u/169439834?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/interhyp-intern-test",
      "html_url": "https://github.com/interhyp-intern-test",
      "followers_url": "https://api.github.com/users/interhyp-intern-test/followers",
      "following_url": "https://api.github.com/users/interhyp-intern-test/following{/other_user}",
      "gists_url": "https://api.github.com/users/interhyp-intern-test/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/interhyp-intern-test/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/interhyp-intern-test/subscriptions",
      "organizations_url": "https://api.github.com/users/interhyp-intern-test/orgs",
      "repos_url": "https://api.github.com/users/interhyp-intern-test/repos",
      "events_url": "https://api.github.com/users/interhyp-intern-test/events{/privacy}",
      "received_events_url": "https://api.github.com/users/interhyp-intern-test/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/interhyp-intern-test/service-metadata",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/interhyp-intern-test/service-metadata",
    "forks_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/forks",
    "keys_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/teams",
    "hooks_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/hooks",
    "issue_events_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/issues/events{/number}",
    "events_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/events",
    "assignees_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/assignees{/user}",
    "branches_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/branches{/branch}",
    "tags_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/tags",
    "blobs_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/languages",
    "stargazers_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/stargazers",
    "contributors_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/contributors",
    "subscribers_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/subscribers",
    "subscription_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/subscription",
    "commits_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/contents/{+path}",
    "compare_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/merges",
    "archive_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/downloads",
    "issues_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/issues{/number}",
    "pulls_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/labels{/name}",
    "releases_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/releases{/id}",
    "deployments_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/deployments",
    "created_at": "2024-10-25T08:07:13Z",
    "updated_at": "2025-04-03T14:01:44Z",
    "pushed_at": "2025-04-04T11:10:52Z",
    "git_url": "git://github.com/interhyp-intern-test/service-metadata.git",
    "ssh_url": "git@github.com:interhyp-intern-test/service-metadata.git",
    "clone_url": "https://github.com/interhyp-intern-test/service-metadata.git",
    "svn_url": "https://github.com/interhyp-intern-test/service-metadata",
    "homepage": "",
    "size": 953,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": false,
    "has_downloads": false,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 3,
    "license": null,
    "allow_forking": false,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "none",
      "techex"
    ],
    "visibility": "internal",
    "forks": 0,
    "open_issues": 3,
    "watchers": 1,
    "default_branch": "main",
    "custom_properties": {
      "commitMessageType": "DEFAULT",
      "owner": "techex",
      "type": "none"
    }
  },
  "organization": {
    "login": "interhyp-intern-test",
    "id": 169439834,
    "node_id": "O_kgDOChlyWg",
    "url": "https://api.github.com/orgs/interhyp-intern-test",
    "repos_url": "https://api.github.com/orgs/interhyp-intern-test/repos",
    "events_url": "https://api.github.com/orgs/interhyp-intern-test/events",
    "hooks_url": "https://api.github.com/orgs/interhyp-intern-test/hooks",
    "issues_url": "https://api.github.com/orgs/interhyp-intern-test/issues",
    "members_url": "https://api.github.com/orgs/interhyp-intern-test/members{/member}",
    "public_members_url": "https://api.github.com/orgs/interhyp-intern-test/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/169439834?v=4",
    "description": "Org for testing configuration changes and automations"
  },
  "enterprise": {
    "id": 154791,
    "slug": "interhyp",
    "name": "Interhyp Gruppe",
    "node_id": "E_kgDOAAJcpw",
    "avatar_url": "https://avatars.githubusercontent.com/b/154791?v=4",
    "description": "",
    "website_url": "",
    "html_url": "https://github.com/enterprises/interhyp",
    "created_at": "2024-05-01T09:45:11Z",
    "updated_at": "2024-12-02T10:49:00Z"
  },
  "sender": {
    "login": "tstollin_interhyp",
    "id": 169138516,
    "node_id": "U_kgDOChTZVA",
    "avatar_url": "https://avatars.githubusercontent.com/u/169138516?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tstollin_interhyp",
    "html_url": "https://github.com/tstollin_interhyp",
    "followers_url": "https://api.github.com/users/tstollin_interhyp/followers",
    "following_url": "https://api.github.com/users/tstollin_interhyp/following{/other_user}",
    "gists_url": "https://api.github.com/users/tstollin_interhyp/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tstollin_interhyp/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tstollin_interhyp/subscriptions",
    "organizations_url": "https://api.github.com/users/tstollin_interhyp/orgs",
    "repos_url": "https://api.github.com/users/tstollin_interhyp/repos",
    "events_url": "https://api.github.com/users/tstollin_interhyp/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tstollin_interhyp/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "installation": {
    "id": 62432934,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uNjI0MzI5MzQ="
  }
}