POST http://localhost:8080/webhooks/vcs/github
Content-Type: application/json
User-Agent: GitHub-Hookshot/e6b9b9c
X-GitHub-Delivery: 4b6cfad0-f8bf-11ef-84fb-f7d0e01b00f2
X-GitHub-Event: check_suite
X-GitHub-Hook-ID: 532001834
X-GitHub-Hook-Installation-Target-ID: 1157269
X-GitHub-Hook-Installation-Target-Type: integration
X-Hub-Signature: sha1=445eac61f0ef776374301d093c2bb76c2632bd06
X-Hub-Signature-256: sha256=076b4d7546bf2375c1908964d6424387a2869159e576a0b62227032766604a91

{
  "action": "requested",
  "check_suite": {
    "id": 35162404203,
    "node_id": "CS_kwDONFp2Fc8AAAAIL9e1aw",
    "head_branch": "test-timeout-fix-validation",
    "head_sha": "d7f6c8971316702f849e80867fe5b909a1603369",
    "status": "queued",
    "conclusion": null,
    "url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/check-suites/35162404203",
    "before": "eeb8989eb47723f2320131621b6c95d9bf21061f",
    "after": "d7f6c8971316702f849e80867fe5b909a1603369",
    "pull_requests": [

    ],
    "app": {
      "id": 1157269,
      "client_id": "Iv23liaaJ2Yue6DAGIqz",
      "slug": "metadata-ih-test",
      "node_id": "A_kwHOChlyWs4AEaiV",
      "owner": {
        "login": "interhyp-intern-test",
        "id": 169439834,
        "node_id": "O_kgDOChlyWg",
        "avatar_url": "https://avatars.githubusercontent.com/u/169439834?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/interhyp-intern-test",
        "html_url": "https://github.com/interhyp-intern-test",
        "followers_url": "https://api.github.com/users/interhyp-intern-test/followers",
        "following_url": "https://api.github.com/users/interhyp-intern-test/following{/other_user}",
        "gists_url": "https://api.github.com/users/interhyp-intern-test/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/interhyp-intern-test/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/interhyp-intern-test/subscriptions",
        "organizations_url": "https://api.github.com/users/interhyp-intern-test/orgs",
        "repos_url": "https://api.github.com/users/interhyp-intern-test/repos",
        "events_url": "https://api.github.com/users/interhyp-intern-test/events{/privacy}",
        "received_events_url": "https://api.github.com/users/interhyp-intern-test/received_events",
        "type": "Organization",
        "user_view_type": "public",
        "site_admin": false
      },
      "name": "Metadata [IH-Test]",
      "description": "",
      "external_url": "https://metadata.core.dev.interhyp-azure.de/swagger-ui",
      "html_url": "https://github.com/apps/metadata-ih-test",
      "created_at": "2025-02-25T07:36:56Z",
      "updated_at": "2025-02-28T09:11:19Z",
      "permissions": {
        "checks": "write",
        "contents": "read",
        "metadata": "read",
        "pull_requests": "write",
        "statuses": "write"
      },
      "events": [
        "check_run",
        "check_suite",
        "pull_request"
      ]
    },
    "created_at": "2025-03-04T06:09:55Z",
    "updated_at": "2025-03-04T06:09:55Z",
    "rerequestable": true,
    "runs_rerequestable": true,
    "latest_check_runs_count": 0,
    "check_runs_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/check-suites/35162404203/check-runs",
    "head_commit": {
      "id": "d7f6c8971316702f849e80867fe5b909a1603369",
      "tree_id": "25e054daa519b75f2aa1378c9a069293067c7e54",
      "message": "RELTEC-12419: test invalid yaml",
      "timestamp": "2025-03-04T06:09:51Z",
      "author": {
        "name": "Stollin, Thomas",
        "email": "thomas.stollin@interhyp.de"
      },
      "committer": {
        "name": "Stollin, Thomas",
        "email": "thomas.stollin@interhyp.de"
      }
    }
  },
  "repository": {
    "id": 878343701,
    "node_id": "R_kgDONFp2FQ",
    "name": "service-metadata",
    "full_name": "interhyp-intern-test/service-metadata",
    "private": true,
    "owner": {
      "login": "interhyp-intern-test",
      "id": 169439834,
      "node_id": "O_kgDOChlyWg",
      "avatar_url": "https://avatars.githubusercontent.com/u/169439834?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/interhyp-intern-test",
      "html_url": "https://github.com/interhyp-intern-test",
      "followers_url": "https://api.github.com/users/interhyp-intern-test/followers",
      "following_url": "https://api.github.com/users/interhyp-intern-test/following{/other_user}",
      "gists_url": "https://api.github.com/users/interhyp-intern-test/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/interhyp-intern-test/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/interhyp-intern-test/subscriptions",
      "organizations_url": "https://api.github.com/users/interhyp-intern-test/orgs",
      "repos_url": "https://api.github.com/users/interhyp-intern-test/repos",
      "events_url": "https://api.github.com/users/interhyp-intern-test/events{/privacy}",
      "received_events_url": "https://api.github.com/users/interhyp-intern-test/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/interhyp-intern-test/service-metadata",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/interhyp-intern-test/service-metadata",
    "forks_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/forks",
    "keys_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/teams",
    "hooks_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/hooks",
    "issue_events_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/issues/events{/number}",
    "events_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/events",
    "assignees_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/assignees{/user}",
    "branches_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/branches{/branch}",
    "tags_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/tags",
    "blobs_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/languages",
    "stargazers_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/stargazers",
    "contributors_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/contributors",
    "subscribers_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/subscribers",
    "subscription_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/subscription",
    "commits_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/contents/{+path}",
    "compare_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/merges",
    "archive_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/downloads",
    "issues_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/issues{/number}",
    "pulls_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/labels{/name}",
    "releases_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/releases{/id}",
    "deployments_url": "https://api.github.com/repos/interhyp-intern-test/service-metadata/deployments",
    "created_at": "2024-10-25T08:07:13Z",
    "updated_at": "2025-03-03T13:40:36Z",
    "pushed_at": "2025-03-04T06:09:54Z",
    "git_url": "git://github.com/interhyp-intern-test/service-metadata.git",
    "ssh_url": "git@github.com:interhyp-intern-test/service-metadata.git",
    "clone_url": "https://github.com/interhyp-intern-test/service-metadata.git",
    "svn_url": "https://github.com/interhyp-intern-test/service-metadata",
    "homepage": "",
    "size": 898,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": false,
    "has_projects": false,
    "has_downloads": false,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 3,
    "license": null,
    "allow_forking": false,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "none",
      "techex"
    ],
    "visibility": "internal",
    "forks": 0,
    "open_issues": 3,
    "watchers": 1,
    "default_branch": "main",
    "custom_properties": {
      "commitMessageType": "DEFAULT",
      "owner": "techex",
      "type": "none"
    }
  },
  "organization": {
    "login": "interhyp-intern-test",
    "id": 169439834,
    "node_id": "O_kgDOChlyWg",
    "url": "https://api.github.com/orgs/interhyp-intern-test",
    "repos_url": "https://api.github.com/orgs/interhyp-intern-test/repos",
    "events_url": "https://api.github.com/orgs/interhyp-intern-test/events",
    "hooks_url": "https://api.github.com/orgs/interhyp-intern-test/hooks",
    "issues_url": "https://api.github.com/orgs/interhyp-intern-test/issues",
    "members_url": "https://api.github.com/orgs/interhyp-intern-test/members{/member}",
    "public_members_url": "https://api.github.com/orgs/interhyp-intern-test/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/169439834?v=4",
    "description": "Org for testing configuration changes and automations"
  },
  "enterprise": {
    "id": 154791,
    "slug": "interhyp",
    "name": "Interhyp Gruppe",
    "node_id": "E_kgDOAAJcpw",
    "avatar_url": "https://avatars.githubusercontent.com/b/154791?v=4",
    "description": "",
    "website_url": "",
    "html_url": "https://github.com/enterprises/interhyp",
    "created_at": "2024-05-01T09:45:11Z",
    "updated_at": "2024-12-02T10:49:00Z"
  },
  "sender": {
    "login": "tstollin_interhyp",
    "id": 169138516,
    "node_id": "U_kgDOChTZVA",
    "avatar_url": "https://avatars.githubusercontent.com/u/169138516?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tstollin_interhyp",
    "html_url": "https://github.com/tstollin_interhyp",
    "followers_url": "https://api.github.com/users/tstollin_interhyp/followers",
    "following_url": "https://api.github.com/users/tstollin_interhyp/following{/other_user}",
    "gists_url": "https://api.github.com/users/tstollin_interhyp/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tstollin_interhyp/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tstollin_interhyp/subscriptions",
    "organizations_url": "https://api.github.com/users/tstollin_interhyp/orgs",
    "repos_url": "https://api.github.com/users/tstollin_interhyp/repos",
    "events_url": "https://api.github.com/users/tstollin_interhyp/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tstollin_interhyp/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "installation": {
    "id": 61630403,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uNjE2MzA0MDM="
  }
}