/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestBuildStatusSetRequest struct for RestBuildStatusSetRequest
type RestBuildStatusSetRequest struct {
    BuildNumber *string `yaml:"buildNumber,omitempty" json:"buildNumber,omitempty"`
    Description *string `yaml:"description,omitempty" json:"description,omitempty"`
    Duration *int64 `yaml:"duration,omitempty" json:"duration,omitempty"`
    Key string `yaml:"key" json:"key"`
    LastUpdated *int64 `yaml:"lastUpdated,omitempty" json:"lastUpdated,omitempty"`
    Name *string `yaml:"name,omitempty" json:"name,omitempty"`
    Parent *string `yaml:"parent,omitempty" json:"parent,omitempty"`
    Ref *string `yaml:"ref,omitempty" json:"ref,omitempty" validate:"regexp=^refs\\/.*"`
    State string `yaml:"state" json:"state"`
    TestResults *RestBuildStatusSetRequestTestResults `yaml:"testResults,omitempty" json:"testResults,omitempty"`
    Url string `yaml:"url" json:"url"`
}
