/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestBuildStats struct for RestBuildStats
type RestBuildStats struct {
    Successful *int32 `yaml:"successful,omitempty" json:"successful,omitempty"`
    Cancelled *int32 `yaml:"cancelled,omitempty" json:"cancelled,omitempty"`
    InProgress *int32 `yaml:"inProgress,omitempty" json:"inProgress,omitempty"`
    Failed *int32 `yaml:"failed,omitempty" json:"failed,omitempty"`
    Unknown *int32 `yaml:"unknown,omitempty" json:"unknown,omitempty"`
}
