/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestSetInsightReportRequest struct for RestSetInsightReportRequest
type RestSetInsightReportRequest struct {
    CoverageProviderKey *string `yaml:"coverageProviderKey,omitempty" json:"coverageProviderKey,omitempty"`
    CreatedDate *int64 `yaml:"createdDate,omitempty" json:"createdDate,omitempty"`
    Data []RestInsightReportData `yaml:"data" json:"data"`
    Details *string `yaml:"details,omitempty" json:"details,omitempty"`
    Link *string `yaml:"link,omitempty" json:"link,omitempty"`
    LogoUrl *string `yaml:"logoUrl,omitempty" json:"logoUrl,omitempty"`
    Reporter *string `yaml:"reporter,omitempty" json:"reporter,omitempty"`
    Result *string `yaml:"result,omitempty" json:"result,omitempty" validate:"regexp=FAIL|PASS"`
    Title string `yaml:"title" json:"title"`
}
