/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestChangesetToCommit struct for RestChangesetToCommit
type RestChangesetToCommit struct {
    Message *string `yaml:"message,omitempty" json:"message,omitempty"`
    CommitterTimestamp *int64 `yaml:"committerTimestamp,omitempty" json:"committerTimestamp,omitempty"`
    Committer *RestChangesetToCommitCommitter `yaml:"committer,omitempty" json:"committer,omitempty"`
    AuthorTimestamp *int64 `yaml:"authorTimestamp,omitempty" json:"authorTimestamp,omitempty"`
    Parents []RestMinimalCommit `yaml:"parents,omitempty" json:"parents,omitempty"`
    Author *RestChangesetToCommitCommitter `yaml:"author,omitempty" json:"author,omitempty"`
    Id *string `yaml:"id,omitempty" json:"id,omitempty"`
    DisplayId *string `yaml:"displayId,omitempty" json:"displayId,omitempty"`
}
