/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestRepositoryPullRequestSettings struct for RestRepositoryPullRequestSettings
type RestRepositoryPullRequestSettings struct {
    MergeConfig *RestPullRequestSettingsMergeConfig `yaml:"mergeConfig,omitempty" json:"mergeConfig,omitempty"`
    RequiredApprovers *RestRepositoryPullRequestSettingsRequiredApprovers `yaml:"requiredApprovers,omitempty" json:"requiredApprovers,omitempty"`
    RequiredAllApprovers *bool `yaml:"requiredAllApprovers,omitempty" json:"requiredAllApprovers,omitempty"`
    RequiredApproversDeprecated *int32 `yaml:"requiredApproversDeprecated,omitempty" json:"requiredApproversDeprecated,omitempty"`
    RequiredSuccessfulBuildsDeprecated *int32 `yaml:"requiredSuccessfulBuildsDeprecated,omitempty" json:"requiredSuccessfulBuildsDeprecated,omitempty"`
    RequiredAllTasksComplete *bool `yaml:"requiredAllTasksComplete,omitempty" json:"requiredAllTasksComplete,omitempty"`
    RequiredSuccessfulBuilds *RestRepositoryPullRequestSettingsRequiredApprovers `yaml:"requiredSuccessfulBuilds,omitempty" json:"requiredSuccessfulBuilds,omitempty"`
}
