/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestRepositoryRefChangeActivity struct for RestRepositoryRefChangeActivity
type RestRepositoryRefChangeActivity struct {
    RefChange *RestRepositoryRefChangeActivityRefChange `yaml:"refChange,omitempty" json:"refChange,omitempty"`
    Repository *RestPullRequestFromRefRepository `yaml:"repository,omitempty" json:"repository,omitempty"`
    Trigger *string `yaml:"trigger,omitempty" json:"trigger,omitempty"`
    Id *int64 `yaml:"id,omitempty" json:"id,omitempty"`
    CreatedDate *int64 `yaml:"createdDate,omitempty" json:"createdDate,omitempty"`
    User *RestPullRequestParticipantUser `yaml:"user,omitempty" json:"user,omitempty"`
}
