/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// ExampleMultipartFormData struct for ExampleMultipartFormData
type ExampleMultipartFormData struct {
        // The branch on which the <code>path</code> should be modified or created.
    Branch *string `yaml:"branch,omitempty" json:"branch,omitempty"`
        // The full content of the file at <code>path</code>.
    Content *string `yaml:"content,omitempty" json:"content,omitempty"`
        // The message associated with this change, to be used as the commit message. Or null if the default message should be used.
    Message *string `yaml:"message,omitempty" json:"message,omitempty"`
        // The starting point for <code>branch</code>. If provided and different from <code>branch</code>, <code>branch</code> will be created as a new branch, branching off from <code>sourceBranch</code>.
    SourceBranch *string `yaml:"sourceBranch,omitempty" json:"sourceBranch,omitempty"`
        // The commit ID of the file before it was edited, used to identify if content has changed. Or null if this is a new file
    SourceCommitId *string `yaml:"sourceCommitId,omitempty" json:"sourceCommitId,omitempty"`
}
