/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestChange struct for RestChange
type RestChange struct {
    Type *string `yaml:"type,omitempty" json:"type,omitempty"`
    Path *RestCommentThreadDiffAnchorPath `yaml:"path,omitempty" json:"path,omitempty"`
    SrcExecutable *bool `yaml:"srcExecutable,omitempty" json:"srcExecutable,omitempty"`
    PercentUnchanged *int32 `yaml:"percentUnchanged,omitempty" json:"percentUnchanged,omitempty"`
    Conflict *RestChangeConflict `yaml:"conflict,omitempty" json:"conflict,omitempty"`
    ContentId *string `yaml:"contentId,omitempty" json:"contentId,omitempty"`
    FromContentId *string `yaml:"fromContentId,omitempty" json:"fromContentId,omitempty"`
    NodeType *string `yaml:"nodeType,omitempty" json:"nodeType,omitempty"`
    Executable *bool `yaml:"executable,omitempty" json:"executable,omitempty"`
    SrcPath *RestCommentThreadDiffAnchorPath `yaml:"srcPath,omitempty" json:"srcPath,omitempty"`
    Links map[string]interface{} `yaml:"-" json:"-"`
}
