/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestWebhook struct for RestWebhook
type RestWebhook struct {
    Name *string `yaml:"name,omitempty" json:"name,omitempty"`
    SslVerificationRequired *bool `yaml:"sslVerificationRequired,omitempty" json:"sslVerificationRequired,omitempty"`
    Statistics map[string]interface{} `yaml:"-" json:"-"`
    ScopeType *string `yaml:"scopeType,omitempty" json:"scopeType,omitempty"`
    Configuration map[string]interface{} `yaml:"configuration,omitempty" json:"configuration,omitempty"`
    Credentials *RestWebhookCredentials `yaml:"credentials,omitempty" json:"credentials,omitempty"`
    Url *string `yaml:"url,omitempty" json:"url,omitempty"`
    Events []string `yaml:"events,omitempty" json:"events,omitempty"`
    Active *bool `yaml:"active,omitempty" json:"active,omitempty"`
}
