/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestApplySuggestionRequest struct for RestApplySuggestionRequest
type RestApplySuggestionRequest struct {
    CommentVersion *RestApplySuggestionRequestCommentVersion `yaml:"commentVersion,omitempty" json:"commentVersion,omitempty"`
    CommitMessage *string `yaml:"commitMessage,omitempty" json:"commitMessage,omitempty"`
    PullRequestVersion *RestApplySuggestionRequestPullRequestVersion `yaml:"pullRequestVersion,omitempty" json:"pullRequestVersion,omitempty"`
    SuggestionIndex *RestApplySuggestionRequestSuggestionIndex `yaml:"suggestionIndex,omitempty" json:"suggestionIndex,omitempty"`
}
