/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient

import "fmt"

type IError interface {
	IsHttpError() bool
}

type HttpError struct {
	err    error
	status int
}

func NewErrorWrap(err error, status int) error {
	return &HttpError{
		err:    err,
		status: status,
	}
}

func NewError(message string, status int) error {
	return &HttpError{
		err:    fmt.Errorf(message),
		status: status,
	}
}

func (e *HttpError) Error() string {
	return e.err.Error()
}

func (e *HttpError) Status() int {
	return e.status
}

func (e *HttpError) IsHttpError() bool {
	return true
}

func IsHttpError(err error) bool {
	_, ok := err.(IError)
	return ok
}
