/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestSingleAddInsightAnnotationRequest struct for RestSingleAddInsightAnnotationRequest
type RestSingleAddInsightAnnotationRequest struct {
    ExternalId *string `yaml:"externalId,omitempty" json:"externalId,omitempty"`
    Line *int32 `yaml:"line,omitempty" json:"line,omitempty"`
    Link *string `yaml:"link,omitempty" json:"link,omitempty"`
    Message string `yaml:"message" json:"message"`
    Path *string `yaml:"path,omitempty" json:"path,omitempty"`
    Severity string `yaml:"severity" json:"severity" validate:"regexp=LOW|MEDIUM|HIGH"`
    Type *string `yaml:"type,omitempty" json:"type,omitempty" validate:"regexp=VULNERABILITY|CODE_SMELL|BUG"`
}
