/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient

import (
    "time"
)

// RestHookScriptConfigScript struct for RestHookScriptConfigScript
type RestHookScriptConfigScript struct {
    Version *int32 `yaml:"version,omitempty" json:"version,omitempty"`
    Name *string `yaml:"name,omitempty" json:"name,omitempty"`
    Id *int64 `yaml:"id,omitempty" json:"id,omitempty"`
    Type *string `yaml:"type,omitempty" json:"type,omitempty"`
    CreatedDate *time.Time `yaml:"createdDate,omitempty" json:"createdDate,omitempty"`
    UpdatedDate *time.Time `yaml:"updatedDate,omitempty" json:"updatedDate,omitempty"`
    Description *string `yaml:"description,omitempty" json:"description,omitempty"`
    PluginKey *string `yaml:"pluginKey,omitempty" json:"pluginKey,omitempty"`
}
