/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestPullRequestFromRefRepositoryOrigin struct for RestPullRequestFromRefRepositoryOrigin
type RestPullRequestFromRefRepositoryOrigin struct {
    Name *string `yaml:"name,omitempty" json:"name,omitempty"`
    Public *bool `yaml:"public,omitempty" json:"public,omitempty"`
    Id *int32 `yaml:"id,omitempty" json:"id,omitempty"`
    State *string `yaml:"state,omitempty" json:"state,omitempty"`
    StatusMessage *string `yaml:"statusMessage,omitempty" json:"statusMessage,omitempty"`
    DefaultBranch *string `yaml:"defaultBranch,omitempty" json:"defaultBranch,omitempty"`
    RelatedLinks map[string]interface{} `yaml:"relatedLinks,omitempty" json:"relatedLinks,omitempty"`
    Partition *int32 `yaml:"partition,omitempty" json:"partition,omitempty"`
    Description *string `yaml:"description,omitempty" json:"description,omitempty"`
    HierarchyId *string `yaml:"hierarchyId,omitempty" json:"hierarchyId,omitempty"`
    Project *RestPullRequestFromRefRepositoryProject `yaml:"project,omitempty" json:"project,omitempty"`
    Scope *string `yaml:"scope,omitempty" json:"scope,omitempty"`
    Slug *string `yaml:"slug,omitempty" json:"slug,omitempty"`
    Forkable *bool `yaml:"forkable,omitempty" json:"forkable,omitempty"`
    Archived *bool `yaml:"archived,omitempty" json:"archived,omitempty"`
    ScmId *string `yaml:"scmId,omitempty" json:"scmId,omitempty"`
    Links map[string]interface{} `yaml:"-" json:"-"`
}
