/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestBranchDeleteRequest struct for RestBranchDeleteRequest
type RestBranchDeleteRequest struct {
        // Don't actually delete the ref name, just do a dry run
    DryRun *bool `yaml:"dryRun,omitempty" json:"dryRun,omitempty"`
        // Commit ID that the provided ref name is expected to point to
    EndPoint *string `yaml:"endPoint,omitempty" json:"endPoint,omitempty"`
        // Name of the ref to be deleted
    Name *string `yaml:"name,omitempty" json:"name,omitempty"`
}
