/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestDetailedInvocation struct for RestDetailedInvocation
type RestDetailedInvocation struct {
    Start *int32 `yaml:"start,omitempty" json:"start,omitempty"`
    Result map[string]interface{} `yaml:"result,omitempty" json:"result,omitempty"`
    Id *int32 `yaml:"id,omitempty" json:"id,omitempty"`
    Duration *int32 `yaml:"duration,omitempty" json:"duration,omitempty"`
    EventScope *RestDetailedInvocationEventScope `yaml:"eventScope,omitempty" json:"eventScope,omitempty"`
    Request map[string]interface{} `yaml:"request,omitempty" json:"request,omitempty"`
    Event *string `yaml:"event,omitempty" json:"event,omitempty"`
    Finish *int32 `yaml:"finish,omitempty" json:"finish,omitempty"`
}
