/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestDiff struct for RestDiff
type RestDiff struct {
    Truncated *bool `yaml:"truncated,omitempty" json:"truncated,omitempty"`
    LineComments []RestComment `yaml:"lineComments,omitempty" json:"lineComments,omitempty"`
    Destination *RestCommentThreadDiffAnchorPath `yaml:"destination,omitempty" json:"destination,omitempty"`
    Source *RestCommentThreadDiffAnchorPath `yaml:"source,omitempty" json:"source,omitempty"`
    Binary *bool `yaml:"binary,omitempty" json:"binary,omitempty"`
    Hunks []RestDiffHunk `yaml:"hunks,omitempty" json:"hunks,omitempty"`
    Properties map[string]interface{} `yaml:"properties,omitempty" json:"properties,omitempty"`
}
