/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient

import (
    "time"
)

// RestSshAccessKeyKey struct for RestSshAccessKeyKey
type RestSshAccessKeyKey struct {
    Id *int32 `yaml:"id,omitempty" json:"id,omitempty"`
    CreatedDate *time.Time `yaml:"createdDate,omitempty" json:"createdDate,omitempty"`
    ExpiryDays *int32 `yaml:"expiryDays,omitempty" json:"expiryDays,omitempty"`
    LastAuthenticated *string `yaml:"lastAuthenticated,omitempty" json:"lastAuthenticated,omitempty"`
    Fingerprint *string `yaml:"fingerprint,omitempty" json:"fingerprint,omitempty"`
    BitLength *int32 `yaml:"bitLength,omitempty" json:"bitLength,omitempty"`
    AlgorithmType *string `yaml:"algorithmType,omitempty" json:"algorithmType,omitempty"`
    Text *string `yaml:"text,omitempty" json:"text,omitempty"`
    Label *string `yaml:"label,omitempty" json:"label,omitempty"`
}
