/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestDeployment struct for RestDeployment
type RestDeployment struct {
    Key *string `yaml:"key,omitempty" json:"key,omitempty"`
    State *string `yaml:"state,omitempty" json:"state,omitempty"`
    DisplayName *string `yaml:"displayName,omitempty" json:"displayName,omitempty"`
    Environment *RestDeploymentEnvironment `yaml:"environment,omitempty" json:"environment,omitempty"`
    FromCommit *RestChangesetFromCommit `yaml:"fromCommit,omitempty" json:"fromCommit,omitempty"`
    ToCommit *RestChangesetFromCommit `yaml:"toCommit,omitempty" json:"toCommit,omitempty"`
    Description *string `yaml:"description,omitempty" json:"description,omitempty"`
    Repository *RestPullRequestFromRefRepository `yaml:"repository,omitempty" json:"repository,omitempty"`
    LastUpdated *int64 `yaml:"lastUpdated,omitempty" json:"lastUpdated,omitempty"`
    Url *string `yaml:"url,omitempty" json:"url,omitempty"`
    DeploymentSequenceNumber *int64 `yaml:"deploymentSequenceNumber,omitempty" json:"deploymentSequenceNumber,omitempty"`
}
