/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestDiffLine struct for RestDiffLine
type RestDiffLine struct {
    Truncated *bool `yaml:"truncated,omitempty" json:"truncated,omitempty"`
    ConflictMarker *string `yaml:"conflictMarker,omitempty" json:"conflictMarker,omitempty"`
    CommentIds []int64 `yaml:"commentIds,omitempty" json:"commentIds,omitempty"`
    Destination *int32 `yaml:"destination,omitempty" json:"destination,omitempty"`
    Source *int32 `yaml:"source,omitempty" json:"source,omitempty"`
    Line *string `yaml:"line,omitempty" json:"line,omitempty"`
}
