/*
Bitbucket Data Center

This is the reference document for the Atlassian Bitbucket REST API. The REST API is for developers who want to:    - integrate Bitbucket with other applications;   - create scripts that interact with Bitbucket; or   - develop plugins that enhance the Bitbucket UI, using REST to interact with the backend.    You can read more about developing Bitbucket plugins in the [Bitbucket Developer Documentation](https://developer.atlassian.com/bitbucket/server/docs/latest/).

API version: 8.19
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bitbucketclient


// RestUserReactionCommentParent struct for RestUserReactionCommentParent
type RestUserReactionCommentParent struct {
    Version *int32 `yaml:"version,omitempty" json:"version,omitempty"`
    Id *int64 `yaml:"id,omitempty" json:"id,omitempty"`
    State *string `yaml:"state,omitempty" json:"state,omitempty"`
    Severity *string `yaml:"severity,omitempty" json:"severity,omitempty"`
    ThreadResolvedDate *int64 `yaml:"threadResolvedDate,omitempty" json:"threadResolvedDate,omitempty"`
    ThreadResolver *RestUserReactionCommentParentThreadResolver `yaml:"threadResolver,omitempty" json:"threadResolver,omitempty"`
        // Indicates if this comment thread has been marked as resolved or not
    ThreadResolved *bool `yaml:"threadResolved,omitempty" json:"threadResolved,omitempty"`
    CreatedDate *int64 `yaml:"createdDate,omitempty" json:"createdDate,omitempty"`
    ResolvedDate *int64 `yaml:"resolvedDate,omitempty" json:"resolvedDate,omitempty"`
    Resolver *RestUserReactionCommentParentThreadResolver `yaml:"resolver,omitempty" json:"resolver,omitempty"`
    UpdatedDate *int64 `yaml:"updatedDate,omitempty" json:"updatedDate,omitempty"`
    Comments []RestComment `yaml:"comments,omitempty" json:"comments,omitempty"`
    Text *string `yaml:"text,omitempty" json:"text,omitempty"`
    Anchor *RestUserReactionCommentParentAnchor `yaml:"anchor,omitempty" json:"anchor,omitempty"`
    Author *RestUserReactionCommentParentThreadResolver `yaml:"author,omitempty" json:"author,omitempty"`
    Html *string `yaml:"html,omitempty" json:"html,omitempty"`
    Anchored *bool `yaml:"anchored,omitempty" json:"anchored,omitempty"`
    Pending *bool `yaml:"pending,omitempty" json:"pending,omitempty"`
    Reply *bool `yaml:"reply,omitempty" json:"reply,omitempty"`
    Properties map[string]interface{} `yaml:"properties,omitempty" json:"properties,omitempty"`
}
