APPLICATION_NAME: metadata

# switch off ECS json logging in favor of readable localhost logs
LOGSTYLE: plain

#BASIC_AUTH_USERNAME: <YOU MUST ADD ANY USERNAME HERE IF VAULT IS DISABLED - SEE README>
#BASIC_AUTH_PASSWORD: <YOU MUST ADD ANY PASSWORD HERE IF VAULT IS DISABLED - SEE README>

BITBUCKET_USERNAME: <YOU MUST ADD THE USERNAME HERE - SEE README>
#BITBUCKET_PASSWORD: <YOU MUST ADD THE PASSWORD HERE IF VAULT IS DISABLED - SEE README>

GIT_COMMITTER_NAME: <YOU MUST ADD SOME COMMITTER NAME HERE - SEE README>
GIT_COMMITTER_EMAIL: <YOU MUST ADD SOME COMMITTER EMAIL HERE - SEE README>

#VAULT_ENABLED: false
VAULT_SERVER: vault.interhyp-intern.de
VAULT_AUTH_TOKEN: <YOU MUST ADD YOUR TOKEN HERE - SEE README>
VAULT_SECRETS_CONFIG: >-
  {
    "some/path/to/secrets": [
      {"vaultKey": "BASIC_AUTH_USERNAME"},
      {"vaultKey": "BASIC_AUTH_PASSWORD"},
      {"vaultKey": "BITBUCKET_PASSWORD"},
      {"vaultKey": "KAFKA_PASSWORD"}
    ]
  }

KEY_SET_URL: https://dex.sys.ehyp.prod.interhyp-cloud.de/keys

METADATA_REPO_URL: https://github.com/Interhyp/service-metadata-example

UPDATE_JOB_INTERVAL_MINUTES: 15
UPDATE_JOB_TIMEOUT_SECONDS: 30

ALERT_TARGET_PREFIX: https://domain.com/
ALERT_TARGET_SUFFIX: '@domain.com'

OWNER_ALIAS_FILTER_REGEX: '.*'
