/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// RefProtections Configures available protections for git refs
type RefProtections struct {
	Branches *RefProtectionsBranches `yaml:"branches,omitempty" json:"branches,omitempty"`
	Tags     *RefProtectionsTags     `yaml:"tags,omitempty" json:"tags,omitempty"`
}
