/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// RepositoryConfigurationWebhooksDto Webhooks configured to the repository.
type RepositoryConfigurationWebhooksDto struct {
	// List of predefined webhooks
	Predefined []string `yaml:"predefined,omitempty" json:"predefined,omitempty"`
	// Additional webhooks to be configured.
	Additional []RepositoryConfigurationWebhookDto `yaml:"additional,omitempty" json:"additional,omitempty"`
}
