/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// ProtectedRef struct for ProtectedRef
type ProtectedRef struct {
	// fnmatch pattern to define protected refs. Must not start with refs/heads/ or refs/tags/. Special value :MAINLINE: matches the currently configured mainline for branch protections.
	Pattern string `yaml:"pattern" json:"pattern" validate:"regexp=^(?!refs\\/(heads|tags)\\/).*$"`
	// list of users or groups for which this protection does not apply.
	Exemptions []string `yaml:"exemptions,omitempty" json:"exemptions,omitempty"`
	// list of group identifiers for which this protection does not apply. This field is read-only and will be filled automatically from the exemptions fields.
	ExemptionsRoles []string `yaml:"exemptionsRoles,omitempty" json:"exemptionsRoles,omitempty"`
}
