/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// ServiceSpecDto struct for ServiceSpecDto
type ServiceSpecDto struct {
	// A relation denoting a dependency on another entity
	DependsOn []string `yaml:"dependsOn,omitempty" json:"dependsOn,omitempty"`
	// A relation with an API, provided by this entity
	ProvidesApis []string `yaml:"providesApis,omitempty" json:"providesApis,omitempty"`
	// A relation with an API, consumed by this entity
	ConsumesApis []string `yaml:"consumesApis,omitempty" json:"consumesApis,omitempty"`
}
