/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// Notification Schema of the Dto sent to all configured downstreams upon a change of service.
type Notification struct {
	// name of the service that was updated
	Name    string               `yaml:"name" json:"name"`
	Event   string               `yaml:"event" json:"event"`
	Type    string               `yaml:"type" json:"type"`
	Payload *NotificationPayload `yaml:"payload,omitempty" json:"payload,omitempty"`
}
