/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// Binary Parameters to identify a binary in e.g. nexus
type Binary struct {
	// The group id of binary
	GroupId string `yaml:"groupId" json:"groupId"`
	// The artifact id of binary
	ArtifactId string `yaml:"artifactId" json:"artifactId"`
	// The version prefix of binary
	VersionPrefix string `yaml:"versionPrefix" json:"versionPrefix"`
	// The classifier of binary
	Classifier *string `yaml:"classifier,omitempty" json:"classifier,omitempty"`
	// The file type of binary e.g. tar.gz
	FileType *string `yaml:"fileType,omitempty" json:"fileType,omitempty"`
}
