/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// OwnerDto struct for OwnerDto
type OwnerDto struct {
	// The contact information of the owner
	Contact string `yaml:"contact" json:"contact"`
	// The teams channel url information of the owner
	TeamsChannelURL *string `yaml:"teamsChannelURL,omitempty" json:"teamsChannelURL,omitempty"`
	// The product owner of this owner space
	ProductOwner *string `yaml:"productOwner,omitempty" json:"productOwner,omitempty"`
	// A list of users which constitute this owner
	Members []string `yaml:"members,omitempty" json:"members,omitempty"`
	// Collection of arbitrary user groups which can be referenced in service configurations. Map of string (group name e.g. some-owner) of strings (list of usernames), one username for each group is required.
	Groups map[string][]string `yaml:"groups,omitempty" json:"groups,omitempty"`
	// A list of users that are allowed to promote services in this owner space
	Promoters []string `yaml:"promoters,omitempty" json:"promoters,omitempty"`
	// The default jira project that is used by this owner space
	DefaultJiraProject *string `yaml:"defaultJiraProject,omitempty" json:"defaultJiraProject,omitempty"`
	// ISO-8601 UTC date time at which this information was originally committed. When sending an update, include the original timestamp you got so we can detect concurrent updates.
	TimeStamp string `yaml:"-" json:"timeStamp"`
	// The git commit hash this information was originally committed under. When sending an update, include the original commitHash you got so we can detect concurrent updates.
	CommitHash string `yaml:"-" json:"commitHash"`
	// The jira issue to use for committing a change, or the last jira issue used.
	JiraIssue string `yaml:"-" json:"jiraIssue"`
	// A display name of the owner, to be presented in user interfaces instead of the owner's name, when available
	DisplayName *string `yaml:"displayName,omitempty" json:"displayName,omitempty"`
	Links       []Link  `yaml:"links,omitempty" json:"links,omitempty"`
}
