/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// RepositoryConfigurationAccessKeyDto struct for RepositoryConfigurationAccessKeyDto
type RepositoryConfigurationAccessKeyDto struct {
	Key        *string `yaml:"key,omitempty" json:"key,omitempty"`
	Data       *string `yaml:"data,omitempty" json:"data,omitempty"`
	Permission *string `yaml:"permission,omitempty" json:"permission,omitempty"`
}
