/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// RepositoryConfigurationWebhookDto struct for RepositoryConfigurationWebhookDto
type RepositoryConfigurationWebhookDto struct {
	Name string `yaml:"name" json:"name"`
	Url  string `yaml:"url" json:"url"`
	// Events the webhook should be triggered with.
	Events        []string          `yaml:"events,omitempty" json:"events,omitempty"`
	Configuration map[string]string `yaml:"configuration,omitempty" json:"configuration,omitempty"`
}
