/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// ServiceListDto struct for ServiceListDto
type ServiceListDto struct {
	Services map[string]ServiceDto `yaml:"services" json:"services"`
	// ISO-8601 UTC date time at which the list of services was obtained from service-metadata
	TimeStamp string `yaml:"-" json:"timeStamp"`
}
