/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"time"
)

// ErrorDto struct for ErrorDto
type ErrorDto struct {
	Details   *string    `yaml:"details,omitempty" json:"details,omitempty"`
	Message   *string    `yaml:"message,omitempty" json:"message,omitempty"`
	Timestamp *time.Time `yaml:"timestamp,omitempty" json:"timestamp,omitempty"`
}
