/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// PullRequests Configures pull request settings
type PullRequests struct {
	// Allows merge commits on pull requests
	AllowMergeCommits *bool `yaml:"allowMergeCommits,omitempty" json:"allowMergeCommits,omitempty"`
	// Allows rebase merging on pull requests
	AllowRebaseMerging *bool `yaml:"allowRebaseMerging,omitempty" json:"allowRebaseMerging,omitempty"`
}
