/*
Metadata

Obtain and manage metadata for owners, services, repositories. Please see [README](https://github.com/Interhyp/metadata-service/blob/main/README.md) for details. **CLIENTS MUST READ!**

API version: v1
Contact: somebody@some-organisation.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

// Quicklink struct for Quicklink
type Quicklink struct {
	Url         *string `yaml:"url,omitempty" json:"url,omitempty"`
	Title       *string `yaml:"title,omitempty" json:"title,omitempty"`
	Description *string `yaml:"description,omitempty" json:"description,omitempty"`
}
