name: Go

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: 📦 Build & Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch,pattern=snapshot-{{sha}}
    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  release:
    name: 🚀 Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          prerelease: false
          allow-initial-development-versions: true # remove to trigger an initial 1.0.0 release
          changelog-generator-opt: "emojis=true"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          TAG=${{ steps.semantic-release.outputs.version }}
          IMAGE=${{ needs.build.outputs.image }}
          
          docker pull $IMAGE
          docker tag $IMAGE ghcr.io/${{ github.repository }}:$TAG
          docker push ghcr.io/${{ github.repository }}:${{ steps.semantic-release.outputs.version }}
